{
 "title": "Node_exporter overall",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Gauge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU  Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MEM Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes* 100) / node_memory_MemTotal_bytes)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (instance)(100 - ((node_filesystem_avail_bytes{device!~'rootfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs'}))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MEM Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes* 100) / node_memory_MemTotal_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(100 - ((node_filesystem_avail_bytes{device!~'rootfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs'}))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}